language: go

services:
  - docker

# Use container based
sudo: false
dist: trusty

go:
  - "1.11.2"

env:
- IMAGE_NAME="liangrog/kctlr-docker-auth"

stages:
  - test
  - docker image build

# Only run build for tags
#if: tag IS present

jobs:  
  include:
    - stage: test
      script:
        - make test
        - make all
        - ls -alt
    - stage: docker image build
      before_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: 
      - make docker_binary
      - docker build . -t $IMAGE_NAME:latest
      - docker build . -t $IMAGE_NAME:$TRAVIS_TAG
      - docker push $IMAGE_NAME:latest
      - docker push $IMAGE_NAME:$TRAVIS_TAG 
      if: tag IS present


