---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "commonMeta" . | indent 4}}
    component: {{ template "fullname" . }}
    role: cluster-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commonMeta" . | indent 4}}
    component: {{ template "fullname" . }}
    role: sa

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "commonMeta" . | indent 4}}
    component: {{ template "fullname" . }}
    role: cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io

